import Foundation
import Alamofire
import StoreKit

// Response models remain the same
struct ValidationResponse: Codable {
    let programId: String?
    
    enum CodingKeys: String, CodingKey {
        case programId = "campaign_id"
    }
}

struct ConversionUser: Codable {
    let externalUserId: String
    let name: String?
    let email: String?
    let phone: String?
    let autoGeneratedExternalUserId: String?
    
    enum CodingKeys: String, CodingKey {
        case externalUserId = "external_user_id"
        case name
        case email
        case phone
        case autoGeneratedExternalUserId = "auto_generated_external_user_id"
    }
}

struct UserRegistrationRequest: Codable {
    let code: String
    let platform: String
    let conversionUser: ConversionUser
    
    enum CodingKeys: String, CodingKey {
        case code
        case platform
        case conversionUser = "conversion_user"
    }
}

public class ShinaraSDK: NSObject, @unchecked Sendable {
    public static let instance = ShinaraSDK()
    private var apiKey: String?
    private var baseURL: String = "https://sdk-gateway-b85kv8d1.ue.gateway.dev"
    
    private let referralCodeKey = "SHINARA_SDK_REFERRAL_CODE"
    private let userExternalIdKey = "SHINARA_SDK_EXTERNAL_USER_ID"
    private let autoGenUserExternalIdKey = "SHINARA_SDK_AUTO_GEN_EXTERNAL_USER_ID"
    private let processedTransactionsKey = "SHINARA_SDK_PROCESSED_TRANSACTIONS"
    private let apiHeaderKey = "X-API-Key"
    
    // Serial queue for thread-safe access to shared resources
    private let queue = DispatchQueue(label: "io.shinara.sdk.queue")

    private override init() {
        super.init()
    }

    public func initialize(apiKey: String) {
        queue.async { [weak self] in
            self?.apiKey = apiKey
            self?.validateAPIKey { result in
                switch result {
                case .success:
                    print("Shinara SDK Initialized")
                case .failure(let error):
                    print("Failed to Initialize Shinara SDK: \(error.localizedDescription)")
                }
            }
        }
    }
    
    private func validateAPIKey(completion: @escaping @Sendable (Result<Void, Error>) -> Void) {
        guard let apiKey = apiKey else {
            DispatchQueue.main.async {
                completion(.failure(NSError(domain: "ShinaraSDK", code: 400, userInfo: [NSLocalizedDescriptionKey: "API Key is not set"])))
            }
            return
        }

        let headers: HTTPHeaders = [apiHeaderKey: apiKey]
        AF.request("\(baseURL)/api/key/validate", headers: headers).response { response in
            DispatchQueue.main.async {
                if let statusCode = response.response?.statusCode {
                    if statusCode == 200 {
                        completion(.success(()))
                    } else {
                        let error = NSError(
                            domain: "ShinaraSDK",
                            code: statusCode,
                            userInfo: [NSLocalizedDescriptionKey: "API Key validation failed"]
                        )
                        completion(.failure(error))
                    }
                } else if let error = response.error {
                    completion(.failure(error))
                } else {
                    completion(.failure(NSError(
                        domain: "ShinaraSDK",
                        code: -1,
                        userInfo: [NSLocalizedDescriptionKey: "Unknown error occurred"]
                    )))
                }
            }
        }
    }

    public func validateReferralCode(code: String, completion: @escaping @Sendable (Result<String, Error>) -> Void) {
        queue.async { [weak self] in
            guard let self = self else { return }
            guard let apiKey = self.apiKey else {
                DispatchQueue.main.async {
                    completion(.failure(NSError(domain: "ShinaraSDK", code: 400, userInfo: [NSLocalizedDescriptionKey: "Shinara SDK API Key is not set."])))
                }
                return
            }

            let parameters = ["code": code]
            let headers: HTTPHeaders = [self.apiHeaderKey: apiKey]

            AF.request(
                "\(self.baseURL)/api/code/validate",
                method: .post,
                parameters: parameters,
                encoder: JSONParameterEncoder.default,
                headers: headers
            ).response { response in
                DispatchQueue.main.async {
                    if let statusCode = response.response?.statusCode {
                        if statusCode == 200 {
                            if let data = response.data {
                                do {
                                    let validationResponse = try JSONDecoder().decode(ValidationResponse.self, from: data)
                                    UserDefaults.standard.set(code, forKey: self.referralCodeKey)
                                    if validationResponse.programId == nil || validationResponse.programId?.isEmpty ?? false {
                                        let error = NSError(
                                            domain: "ShinaraSDK",
                                            code: statusCode,
                                            userInfo: [NSLocalizedDescriptionKey: "Referral code validation failed"]
                                        )
                                        completion(.failure(error))
                                    } else {
                                        completion(.success(validationResponse.programId ?? ""))
                                    }
                                } catch {
                                    completion(.failure(NSError(
                                        domain: "ShinaraSDK",
                                        code: -1,
                                        userInfo: [NSLocalizedDescriptionKey: "Unknown error occurred"]
                                    )))
                                }
                            } else {
                                completion(.failure(NSError(
                                    domain: "ShinaraSDK",
                                    code: -1,
                                    userInfo: [NSLocalizedDescriptionKey: "Unknown error occurred"]
                                )))
                            }
                        } else {
                            let error = NSError(
                                domain: "ShinaraSDK",
                                code: statusCode,
                                userInfo: [NSLocalizedDescriptionKey: "Referral code validation failed"]
                            )
                            completion(.failure(error))
                        }
                    } else if let error = response.error {
                        completion(.failure(error))
                    } else {
                        completion(.failure(NSError(
                            domain: "ShinaraSDK",
                            code: -1,
                            userInfo: [NSLocalizedDescriptionKey: "Unknown error occurred"]
                        )))
                    }
                }
            }
        }
    }
    
    public func getReferralCode() -> String? {
        queue.sync {
            return UserDefaults.standard.string(forKey: referralCodeKey)
        }
    }

    public func registerUser(userId: String, email: String?, name: String?, phone: String?, completion: @escaping @Sendable (Result<Void, Error>) -> Void) {
            queue.async { [weak self] in
                guard let self = self else { return }
                guard let apiKey = self.apiKey else {
                    DispatchQueue.main.async {
                        completion(.failure(NSError(domain: "ShinaraSDK", code: 400, userInfo: [NSLocalizedDescriptionKey: "API Key is not set."])))
                    }
                    return
                }
                
                guard let referralCode = UserDefaults.standard.string(forKey: self.referralCodeKey) else {
                    DispatchQueue.main.async {
                        completion(.failure(NSError(domain: "ShinaraSDK", code: 400, userInfo: [NSLocalizedDescriptionKey: "No stored referral code found. Please save a referral code before registering a user."])))
                    }
                    return
                }

                let headers: HTTPHeaders = [self.apiHeaderKey: apiKey]
                                
                let conversionUser = ConversionUser(
                    externalUserId: userId,
                    name: name,
                    email: email,
                    phone: phone,
                    autoGeneratedExternalUserId: UserDefaults.standard.string(forKey: self.autoGenUserExternalIdKey)
                )
                
                let request = UserRegistrationRequest(
                    code: referralCode,
                    platform: "",
                    conversionUser: conversionUser
                )

                AF.request(
                    "\(self.baseURL)/newuser",
                    method: .post,
                    parameters: request,
                    encoder: JSONParameterEncoder.default,
                    headers: headers
                ).response { response in
                    DispatchQueue.main.async {
                        if let statusCode = response.response?.statusCode {
                            if statusCode == 200 {
                                UserDefaults.standard.set(userId, forKey: self.userExternalIdKey)
                                // remove auto-generated external user ID now that we have a real one
                                UserDefaults.standard.removeObject(forKey: self.autoGenUserExternalIdKey)
                                completion(.success(()))
                            } else {
                                let error = NSError(
                                    domain: "ShinaraSDK",
                                    code: statusCode,
                                    userInfo: [NSLocalizedDescriptionKey: "User registration failed"]
                                )
                                completion(.failure(error))
                            }
                        } else if let error = response.error {
                            completion(.failure(error))
                        } else {
                            completion(.failure(NSError(
                                domain: "ShinaraSDK",
                                code: -1,
                                userInfo: [NSLocalizedDescriptionKey: "Unknown error occurred"]
                            )))
                        }
                    }
                }
            }
        }
    
    public func getUserId() -> String? {
        queue.sync {
            return UserDefaults.standard.string(forKey: userExternalIdKey)
        }
    }
    
    public func attributePurchase(productId: String, transactionId: String, completion: @escaping @Sendable (Result<Void, Error>) -> Void) {
        queue.async { [weak self] in
            guard let self = self else { return }
            guard let apiKey = self.apiKey else {
                DispatchQueue.main.async {
                    completion(.failure(NSError(domain: "ShinaraSDK", code: 400, userInfo: [NSLocalizedDescriptionKey: "API Key is not set."])))
                }
                return
            }
            
            guard let referralCode = UserDefaults.standard.string(forKey: self.referralCodeKey) else {
                DispatchQueue.main.async {
                    completion(.success(()))
                }
                return
            }

            // Check if the transaction ID is already processed
            var processedTransactions = UserDefaults.standard.array(forKey:  self.processedTransactionsKey) as? [String] ?? []
            if processedTransactions.contains(transactionId) {
                // Skip processing if the transaction ID is already handled
                DispatchQueue.main.async {
                    completion(.success(()))
                }
                return
            }

            let headers: HTTPHeaders = [self.apiHeaderKey: apiKey]
            
            var parameters: [String: String] = [
                "product_id": productId,
                "transaction_id": transactionId,
                "code": referralCode,
                "platform": ""
            ]
            
            if let externalUserId = UserDefaults.standard.string(forKey: self.userExternalIdKey) {
                parameters["external_user_id"] = externalUserId
            } else {
                let autoSDKGenExternalUserId: String = UUID().uuidString
                UserDefaults.standard.set(autoSDKGenExternalUserId, forKey: self.autoGenUserExternalIdKey)
                parameters["auto_generated_external_user_id"] = autoSDKGenExternalUserId
            }

            AF.request(
                "\(self.baseURL)/iappurchase",
                method: .post,
                parameters: parameters,
                encoding: JSONEncoding.default,
                headers: headers
            ).response { response in
                DispatchQueue.main.async {
                    if let statusCode = response.response?.statusCode {
                        if statusCode == 200 {
                            // Add transaction ID to the processed list
                            self.queue.async {
                                processedTransactions.append(transactionId)
                                UserDefaults.standard.set(processedTransactions, forKey: self.processedTransactionsKey)
                            }
                            completion(.success(()))
                        } else {
                            let error = NSError(
                                domain: "ShinaraSDK",
                                code: statusCode,
                                userInfo: [NSLocalizedDescriptionKey: "Purchase attribution failed"]
                            )
                            completion(.failure(error))
                        }
                    } else if let error = response.error {
                        completion(.failure(error))
                    } else {
                        completion(.failure(NSError(
                            domain: "ShinaraSDK",
                            code: -1,
                            userInfo: [NSLocalizedDescriptionKey: "Unknown error occurred"]
                        )))
                    }
                }
            }
        }
    }

    deinit {
    }
}
